// Getters
export const PROFILE_SEED = 'profile/SEED';
export const PROFILE_AVATAR = 'profile/AVATAR'
export const DOCUMENTS_COUNT = 'DOCUMENTS_COUNT'
export const DOCUMENT_ITEMS = 'DOCUMENT_ITEMS'
export const REQUEST_FILE = "REQUEST_FILE"
export const REQUEST_CONTENT = "REQUEST_CONTENT"
export const REQUEST_RECIPIENTS = "REQUEST_RECIPIENTS"

// Mutations
export const PROFILE_CHANGE_SEED = 'profile/CHANGE_SEED';
export const UPDATE_DOCUMENT_COUNTS = 'UPDATE_DOCUMENT_COUNTS'
export const UPDATE_DOCUMENT_ITEMS = 'UPDATE_DOCUMENT_ITEMS'
export const CHANGE_DOCUMENTS_FOLDER = 'CHANGE_DOCUMENTS_FOLDER'
export const REQUEST_UPDATE_FILE = "REQUEST_UPDATE_FILE"
export const REQUEST_UPDATE_CONTENT = "REQUEST_UPDATE_CONTENT"
export const REQUEST_UPDATE_RECIPIENTS = "REQUEST_UPDATE_RECIPIENTS"
export const REQUEST_CLEAR = "REQUEST_CLEAR"


// Actions
export const PROFILE_UPDATE_SEED = 'profile/UPDATE_SEED'
export const REQUEST_DOCUMENT_COUNTS = 'REQUEST_DOCUMENT_COUNTS'
export const SELECT_DOCUMENT_FOLDER = 'SELECT_DOCUMENT_FOLDER'
export const REQUEST_SET_FILE = "REQUEST_SET_FILE"
export const REQUEST_SET_CONTENT = "REQUEST_SET_CONTENT"
export const REQUEST_SET_RECIPIENTS = "REQUEST_SET_RECIPIENTS"
export const REQUEST_SEND = "REQUEST_SEND"
